default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: db
  port: 5432

development:
  <<: *default
  database: school_service_development

test:
  <<: *default
  database: school_service_test

production:
  <<: *default
  database: school_service_production
 
